"""create mystery_media table

Revision ID: 977678698f70
Revises: 41dc65ee3966
Create Date: 2025-05-23 12:21:33.963712

"""

import sqlalchemy as sa

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "977678698f70"
down_revision: Union[str, None] = "41dc65ee3966"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mystery_media",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("mystery_id", sa.String(), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_mystery_media_id"), "mystery_media", ["id"], unique=False)
    op.create_index(
        op.f("ix_mystery_media_mystery_id"), "mystery_media", ["mystery_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_mystery_media_mystery_id"), table_name="mystery_media")
    op.drop_index(op.f("ix_mystery_media_id"), table_name="mystery_media")
    op.drop_table("mystery_media")
    # ### end Alembic commands ###
