"""initial_schema

Revision ID: c5ce804f44b1
Revises: 
Create Date: 2026-04-07 05:54:44.530655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5ce804f44b1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_timeline_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clientFacingId', sa.String(), sa.Computed('CASE WHEN "group" = \'MOUSE\' THEN \'mouse-\' || id ELSE \'keyboard-\' || id END', persisted=True), nullable=True),
    sa.Column('group', sa.Enum('MOUSE', 'KEYBOARD', name='charteventtype'), nullable=True),
    sa.Column('content', sa.String(), sa.Computed('CASE WHEN "group" = \'MOUSE\' THEN \'Mouse Event \' || id ELSE \'Typing Session \' || id END', persisted=True), nullable=True),
    sa.Column('start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_timeline_entries_id'), 'client_timeline_entries', ['id'], unique=False)
    op.create_table('daily_chrome_summaries',
    sa.Column('domain_name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hours_spent', sa.Float(), nullable=False),
    sa.Column('gathering_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gathering_date_local', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_chrome_summaries_id'), 'daily_chrome_summaries', ['id'], unique=False)
    op.create_table('daily_program_summaries',
    sa.Column('exe_path_as_id', sa.String(), nullable=False),
    sa.Column('process_name', sa.String(), nullable=False),
    sa.Column('program_name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hours_spent', sa.Float(), nullable=False),
    sa.Column('gathering_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gathering_date_local', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_program_summaries_id'), 'daily_program_summaries', ['id'], unique=False)
    op.create_table('daily_video_summaries',
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('media_name', sa.String(), nullable=True),
    sa.Column('channel_name', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hours_spent', sa.Float(), nullable=False),
    sa.Column('gathering_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gathering_date_local', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_video_summaries_id'), 'daily_video_summaries', ['id'], unique=False)
    op.create_table('domain_logs',
    sa.Column('domain_name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hours_spent', sa.Float(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_time_local', sa.DateTime(), nullable=False),
    sa.Column('end_time_local', sa.DateTime(), nullable=False),
    sa.Column('duration_in_sec', sa.Float(), nullable=True),
    sa.Column('gathering_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gathering_date_local', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_logs_id'), 'domain_logs', ['id'], unique=False)
    op.create_table('mouse_moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mouse_moves_id'), 'mouse_moves', ['id'], unique=False)
    op.create_table('mystery_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mystery_id', sa.String(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mystery_media_id'), 'mystery_media', ['id'], unique=False)
    op.create_index(op.f('ix_mystery_media_mystery_id'), 'mystery_media', ['mystery_id'], unique=False)
    op.create_table('precomputed_timelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clientFacingId', sa.String(), nullable=True),
    sa.Column('group', sa.Enum('MOUSE', 'KEYBOARD', name='charteventtype'), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('eventCount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_precomputed_timelines_id'), 'precomputed_timelines', ['id'], unique=False)
    op.create_table('program_logs',
    sa.Column('exe_path_as_id', sa.String(), nullable=False),
    sa.Column('process_name', sa.String(), nullable=False),
    sa.Column('program_name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hours_spent', sa.Float(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_time_local', sa.DateTime(), nullable=False),
    sa.Column('end_time_local', sa.DateTime(), nullable=False),
    sa.Column('duration_in_sec', sa.Float(), nullable=True),
    sa.Column('gathering_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gathering_date_local', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_logs_id'), 'program_logs', ['id'], unique=False)
    op.create_table('system_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('program_started', 'online', 'shutdown', name='systemstatustype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_status_id'), 'system_status', ['id'], unique=False)
    op.create_table('typing_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_typing_sessions_id'), 'typing_sessions', ['id'], unique=False)
    op.create_table('video_logs',
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('media_name', sa.String(), nullable=False),
    sa.Column('channel_name', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hours_spent', sa.Float(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_time_local', sa.DateTime(), nullable=False),
    sa.Column('end_time_local', sa.DateTime(), nullable=False),
    sa.Column('duration_in_sec', sa.Float(), nullable=True),
    sa.Column('gathering_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gathering_date_local', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_logs_id'), 'video_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_logs_id'), table_name='video_logs')
    op.drop_table('video_logs')
    op.drop_index(op.f('ix_typing_sessions_id'), table_name='typing_sessions')
    op.drop_table('typing_sessions')
    op.drop_index(op.f('ix_system_status_id'), table_name='system_status')
    op.drop_table('system_status')
    op.drop_index(op.f('ix_program_logs_id'), table_name='program_logs')
    op.drop_table('program_logs')
    op.drop_index(op.f('ix_precomputed_timelines_id'), table_name='precomputed_timelines')
    op.drop_table('precomputed_timelines')
    op.drop_index(op.f('ix_mystery_media_mystery_id'), table_name='mystery_media')
    op.drop_index(op.f('ix_mystery_media_id'), table_name='mystery_media')
    op.drop_table('mystery_media')
    op.drop_index(op.f('ix_mouse_moves_id'), table_name='mouse_moves')
    op.drop_table('mouse_moves')
    op.drop_index(op.f('ix_domain_logs_id'), table_name='domain_logs')
    op.drop_table('domain_logs')
    op.drop_index(op.f('ix_daily_video_summaries_id'), table_name='daily_video_summaries')
    op.drop_table('daily_video_summaries')
    op.drop_index(op.f('ix_daily_program_summaries_id'), table_name='daily_program_summaries')
    op.drop_table('daily_program_summaries')
    op.drop_index(op.f('ix_daily_chrome_summaries_id'), table_name='daily_chrome_summaries')
    op.drop_table('daily_chrome_summaries')
    op.drop_index(op.f('ix_client_timeline_entries_id'), table_name='client_timeline_entries')
    op.drop_table('client_timeline_entries')
    # ### end Alembic commands ###
