repos:
    - repo: local
      hooks:
          - id: sync-types
            name: Sync TypeScript types
            entry: python activitytracker/scripts/sync_types.py
            language: system
            files: '.*\.py$' # Only run when Python files change
            pass_filenames: false
