# pyproject.toml

[tool.isort]
profile = "black"
# Include the standard sections along with your custom ones
sections = [
    "FUTURE",
    "STDLIB",
    "THIRDPARTY",
    "PARTY1",
    "PARTY2",
    "PARTY3",
    "PARTY4",
    "FIRSTPARTY",
    "LOCALFOLDER",
]
known_party1 = ["pytest", "unittest"]
known_party2 = ["asyncio", "sqlalchemy"]
known_party3 = ["pytz", "datetime", "time"]
known_party4 = ["typing"]
known_third_party = ["sqlalchemy"] # Add this line

multi_line_output = 3

[tool.black]
line-length = 93


[tool.pytest.ini_options]
testpaths = ["tests"] # Look for tests here
